### ISSUE TITLE
Upload Resume

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_PETS#1]
As a Job Developer, 
While logged into PETS, 
I can upload a résumé, 
And create a profile for, a Job Seeker

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by patmbolger** [comment]
Need to rewrite the task description consistent with roles/interactions discovery.  For example: "As a Job Developer, while logged into PETS for my Job Agency, I can upload a résumé, and create a profile for, a Job Seeker."

**Comment by joaopapereira** [comment]
Waiting on feedback from the client

**Comment by joaopapereira** [comment]
This issue was moved to AgileVentures/MetPlus_tracker#1
