### ISSUE TITLE
Upload Resume

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_PETS#12]
As a Case Manager,
While visiting the website www.metplus.org
I can upload a resume in behalf or a Job Seeker

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by patmbolger** [comment]
Note this action (adding a JS résumé to PETS) by the case manager also includes: 1) creating an account in PETS for the JS, 2) filling out the JS profile, and 3) establishing an association between the JS and the Job Agency where the case manager works.

**Comment by joaopapereira** [comment]
This issue was moved to AgileVentures/MetPlus_tracker#25
