### ISSUE TITLE
BUG: layout footer detached

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_PETS#128]
When I display a PETS page in a browser window with a vertical dimension smaller than the content on that page, when I scroll down (to see rest of content) the footer travels up with the page (it becomes detached from the bottom of the window)

**Comment by joaopapereira** [comment]
Is this a bug report?
If so maybe we should centralize this is the teacher project

**Comment by patmbolger** [comment]
It is a bug report.  Not sure what you mean by "teacher project"?

**Comment by joaopapereira** [comment]
It was auto correct from the phone.....
I meant tracker repository

**Comment by patmbolger** [comment]
Curious .... when I created this issue in waffle yesterday, I was unable to assign the "Bug" label to it.  I just tried to do so now and am still not able to do that.

**Comment by joaopapereira** [comment]
You cannot, because you are in MetPlus_PETS project you can only do that in MetPlus_tracker.
You should open the ticket there
