### ISSUE TITLE
Job search by Case Manager to a Job Seeker

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_PETS#19]
As a Case Manager
Given a Job Seeker skills
The system search for matches of jobs

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by joaopapereira** [comment]
Asked the client if this requirement is correct

**Comment by patmbolger** [comment]
We assume this feature is also available (or exclusively available?) to Job Developers.  Please confirm.

**Comment by joaopapereira** [comment]
This issue was moved to AgileVentures/MetPlus_tracker#18
