### ISSUE TITLE
Post Job - not affiliated with agency

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_PETS#2]
PETS-5: As an Employer not affiliated with the agency,
While visiting the website www.metplus.org
I can add a new job description
And send it to all subscribers

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by patmbolger** [comment]
This action is not supported by the "Roles and interactions" document.  (that document, in fact, lacks interaction descriptions for Employer <> Job Agency - we should add that).

**Comment by patmbolger** [comment]
Also, see PETS-22 (these might be in conflict)

**Comment by patmbolger** [comment]
Actually, see PETS-16 and PETS-23

**Comment by joaopapereira** [comment]
We will ask the client if we can have Employers that are not affiliated with one agency.

**Comment by joaopapereira** [comment]
This issue was moved to AgileVentures/MetPlus_tracker#2
