### ISSUE TITLE
Process Resume

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_PETS#22]
PETS-20: As the System 
After receiving a Resume 
Generate Meta data relevant to help on job search

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by joaopapereira** [comment]
- [ ] Task 9 completed
- [ ] Create a process that will search all the Resumes that need to be processed and process them

**Comment by mtc2013** [comment]
Test

**Comment by joaopapereira** [comment]
This issue was moved to AgileVentures/MetPlus_tracker#17
