### ISSUE TITLE
Job Seeker applies to Job

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_PETS#3]
As a Job Seeker,
When I go to a Job Fair
I talk with employer 
And if I am interested I give my email address and my Agency to the employer so that he can check my Resume

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by patmbolger** [comment]
Changes: 
1) Use "email address" instead of ID
2) Also, JS tells employer the job agency he/she is associated with

**Comment by joaopapereira** [comment]
Changes made

**Comment by joaopapereira** [comment]
This issue was moved to AgileVentures/MetPlus_tracker#3
