### ISSUE TITLE
Registration Employer

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_PETS#32]
As and Administrator
When a new Employer registers in the website
I will be notified
Then I need to review the information of the Employer
And accept or reject the application, notifying the Employer

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by vijayakarumudi** [comment]
As an Administrator of the system. you can review the registration information  and accept the Employer.

**Comment by joaopapereira** [comment]
This issue was moved to AgileVentures/MetPlus_tracker#12
