### ISSUE TITLE
Refresh all tasks when one of them is changed

### ISSUE THREAD

**Issue by dsmegha** [AgileVentures/MetPlus_PETS#365]
I have my code at https://github.com/dsmegha/MetPlus_PETS/tree/View-closed-tasks-%23342.

When a user (admin/jobdeveloper) is in his homepage, only his open tasks are shown. I am changing this to include showing his closed task too.
Whenever the user edits a tasks, for example finishes working on it, the js code makes sure that particular task is removed from his present view, by reloading the entire div containing all these tasks.

```<div class="pagination-div" data-url="/tasks/tasks/agency-closed" id="tasks-mine-open">```

However I used simple bootstrap tabs, and I want to refresh the other div, the div containing closed tasks as well, so that the task now appears there

```
this.done_task = function() {
        var url = $(this).data("url");
        $.ajax({type: 'PATCH',
            url: url,
            data: {},
            timeout: 5000,
            success: function (){
                Notification.success_notification('Work on the task is done');
                self.refresh_tasks();
            },
            error: function (xhrObj, status, exception) {
                Notification.error_notification(xhrObj.responseJSON['message']);
            }
        });
        return false;
    };
```

The js where we call the refresh_tasks

```
this.refresh_tasks = function () {
        self.unsetTaskHolder();
        $("#" + self.holder_id).trigger('pagination:reload');
    };
```

Instead of  `self.refresh_tasks();` would it be possible to call the refresh_tasks on all divs with ids starting with tasks- maybe?

**Comment by tansaku** [comment]
I can't speak to the bigger picture advisability, but this might help: http://stackoverflow.com/questions/11496645/how-to-get-css-to-select-id-that-begins-with-a-string-not-in-javascript
