### ISSUE TITLE
Employer <> Agency relationship

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_PETS#47]
The P.E.T.S. system description contains this: "If the employers are linked to a work agency they are able to post a job to the agency cloud server in which will notify the job developer of the new positions."  We need to clarify what it means for an employer to be "linked to" a jobs agency.  And, what are the constraints imposed (in the system) by that relationship?  For instance, if an employer has such a relationship, does this mean that the employer cannot post a job to the site directly, but always has to have the agency post their jobs?

**Comment by joaopapereira** [comment]
Does this mean that when an employer post a job in our system their Agency will be notified?
What does link between employer and agency mean?
  - The Agency will post the job offer for the employer?
  - The employer will be able to post a job offer without notifying the agency about that?
  - If a fee is due between agency and employer should PETS be used?

**Comment by patmbolger** [comment]
After discussion with Chet (Sep 26, 2015): An employer can *always* post a job directly to the site.  When that happens, any agency which has a relationship with the employer is notified of the new job posting and can then take action as appropriate.

**Comment by patmbolger** [comment]
Also, all agencies and job developers are non-profit is these situations.  There are no monetary considerations involved in the interactions between these actors.

**Comment by patmbolger** [comment]
I think we can close this issue.  It has been explored and the results documented in "roles and interactions" document.
