### ISSUE TITLE
Resume Form as Job Developer

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_PETS#51]
As a Job Developer or Case Manager
I want to edit the Resume information of a Job Seeker using a form

**Comment by vijayakarumudi** [comment]
As a  Job Developer or Case Manager send  required  information to the Job Seeker. Job Seeker edit the Resume.

**Comment by vijayakarumudi** [comment]
As a  Job Developer or Case Manager send  required  information to the Job Seeker. Job Seeker edit the Resume.

**Comment by joaopapereira** [comment]
This issue was moved to AgileVentures/MetPlus_tracker#5
