### ISSUE TITLE
Implementation investigation/design

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_PETS#53]
Since we have multiple roles in the system we should begin thinking about some implementation ideas now, including:

1) Managing logins and authentication - we have a nice and simple login mechanism now - will that suffice, or should we look at Devise (or similar gem?) to help manage all of that (including "forgot password", "password reset", etc. actions.

2) Since each role has potentially many actions it can or cannot take, we should look at appropriate gems that might help manage that (e.g. Cancancan or similar).

3) Other areas to investigate ....?

**Comment by patmbolger** [comment]
ERD (entity-relationship diagram)

**Comment by joaopapereira** [comment]
This issue was moved to AgileVentures/MetPlus_tracker#4
