### ISSUE TITLE
Job Seeker apply to job 

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_PETS#8]
As a Job Seeker
When I apply to job that I am not qualified for
I get rejected and information is sent to Job Developer

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by patmbolger** [comment]
As a Job Seeker
I want to apply to jobs on the Job Agency site with which I am associated
And when I apply to a job that I am not qualified for
I get rejected and information is sent to my Job Developer at the Job Agency

**Comment by joaopapereira** [comment]
Change done

**Comment by joaopapereira** [comment]
This issue was moved to AgileVentures/MetPlus_tracker#29
