### ISSUE TITLE
Upload Resume - Job Seeker

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_PETS#9]
PETS-2: As a Job Seeker,
While visiting the website www.metplus.org
I can upload my resume

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by joaopapereira** [comment]
- [ ] Prepare PETS to upload Resume
 - [ ] Create Service class
 - [ ] Create connectivity method
 - [ ] Create field in registration form for resume upload
- [ ] Prepare ResumeCruncher to upload Resume
 - [ ] Create database object to store the Resume and the meta data
 - [ ] Create class to parse pdf and word file into the object
 - [ ] Create controller for resume
 - [ ] Create endpoint to upload Resume

**Comment by patmbolger** [comment]
Is this feature wanted by the client (we do not list this action in the "Roles and interactions" document)?

**Comment by joaopapereira** [comment]
In this story we implement the feature to upload the resume to the Resume Cruncher. We will ask the client if a Job Seeker can create an account. If not we can remove the sub task "Create field in registration form for resume upload"

**Comment by joaopapereira** [comment]
This issue was moved to AgileVentures/MetPlus_tracker#28
